### ISSUE TITLE
建表数量是否过多

### ISSUE THREAD

**Issue by Scott221-ax** [Hu-xiaojiao/12306-code-database-2023-12-15#1]
通过观察博主.db文件可知,对于某个车次有单独的一张表存储其的时刻表信息.
以`"G"`文件夹举例,`"full_code_index.db"`中的`"index"`表存有4689条记录,意味着相对应的需要建4689张表来存储每个车次的时刻表信息,这是否会导致表数过多且单张表记录较少的问题,拖累数据库性能.

> 阿里巴巴《Java 开发手册》提出单表行数超过 500 万行或者单表容量超过 2GB，才推荐进行分库分表.

本人也是在校学生,不清楚业内针对此问题的主流解决办法,提出个人看法,还望博主解惑.

**Comment by Huxiaojiao233** [comment]
首先非常感谢你的提问
本人也是在校学生，这个项目建立的时候我还没学数据库，只是自己拿来练习Python爬虫顺手上传的一个结果
在我看来，由于铁路现行的各类车次均有不同的停车站与停站时间，用一个表来存储不同的车次不是很好处理，查询时也不方便，所以我选择的是分表存储不同的车次数据。而且这个数据库一般来说不会修改其内部数据，只是为了查询使用，建立好之后就不太需要修改这个库了。
其实这个库是我用来做别的项目来建的，所以说我只能怎么方便怎么来，我也是从我服务器方面考虑，直接处理好表，然后通过接口传输数据就行，不用再过多计算啥的。
我也不太专业，等我这学期把数据库原理学完再看看能不能优化吧:)
